// 
// This source code was auto-generated by xsd, Version=4.0.30319.18020.
// 

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.6387
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml;
using System.Xml.Serialization;

namespace FolderPoll.Core
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class FolderPollConfig
    {

        private Poll[] pollField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Poll")]
        public Poll[] Poll
        {
            get
            {
                return this.pollField;
            }
            set
            {
                this.pollField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class Poll
    {

        private NewFile newFileField;

        private string folderField;

        private bool impersonationField;

        private bool impersonationFieldSpecified;

        private string usernameField;

        private string passwordField;

        private string domainField;

        /// <remarks/>
        public NewFile NewFile
        {
            get
            {
                return this.newFileField;
            }
            set
            {
                this.newFileField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Folder
        {
            get
            {
                return this.folderField;
            }
            set
            {
                this.folderField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Impersonation
        {
            get
            {
                return this.impersonationField;
            }
            set
            {
                this.impersonationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ImpersonationSpecified
        {
            get
            {
                return !string.IsNullOrEmpty(this.Username);
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Domain
        {
            get
            {
                return this.domainField;
            }
            set
            {
                this.domainField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class NewFile
    {

        private NewFileCopy copyField;

        private NewFileMove moveField;

        private NewFileLaunch launchField;

        private string filterField;

        /// <remarks/>
        public NewFileCopy Copy
        {
            get
            {
                return this.copyField;
            }
            set
            {
                this.copyField = value;
            }
        }

        /// <remarks/>
        public NewFileMove Move
        {
            get
            {
                return this.moveField;
            }
            set
            {
                this.moveField = value;
            }
        }

        /// <remarks/>
        public NewFileLaunch Launch
        {
            get
            {
                return this.launchField;
            }
            set
            {
                this.launchField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Filter
        {
            get
            {
                return this.filterField;
            }
            set
            {
                this.filterField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class NewFileCopy
    {

        private string targetFolderField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TargetFolder
        {
            get
            {
                return this.targetFolderField;
            }
            set
            {
                this.targetFolderField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class NewFileMove
    {

        private string targetFolderField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TargetFolder
        {
            get
            {
                return this.targetFolderField;
            }
            set
            {
                this.targetFolderField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class NewFileLaunch
    {

        private string applicationField;

        private string argumentsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Application
        {
            get
            {
                return this.applicationField;
            }
            set
            {
                this.applicationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Arguments
        {
            get
            {
                return this.argumentsField;
            }
            set
            {
                this.argumentsField = value;
            }
        }
    }

    /* 
    //Old XML
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class FolderPoll
    {
        private Poll[] pollField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Poll")]
        public Poll[] Poll
        {
            get
            {
                return this.pollField;
            }
            set
            {
                this.pollField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class Poll
    {
        private NewFile newFileField;

        private string folderField;

        private bool impersonationField;

        private bool impersonationFieldSpecified;

        private string usernameField;

        private string passwordField;

        /// <remarks/>
        public NewFile NewFile
        {
            get
            {
                return this.newFileField;
            }
            set
            {
                this.newFileField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Folder
        {
            get
            {
                return this.folderField;
            }
            set
            {
                this.folderField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Impersonation
        {
            get
            {
                return this.impersonationField;
            }
            set
            {
                this.impersonationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ImpersonationSpecified
        {
            get
            {
                return this.impersonationFieldSpecified;
            }
            set
            {
                this.impersonationFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class NewFile
    {
        private NewFileCopy copyField;

        private NewFileMove moveField;

        private NewFileLaunch launchField;

        private string filterField;

        /// <remarks/>
        public NewFileCopy Copy
        {
            get
            {
                return this.copyField;
            }
            set
            {
                this.copyField = value;
            }
        }

        /// <remarks/>
        public NewFileMove Move
        {
            get
            {
                return this.moveField;
            }
            set
            {
                this.moveField = value;
            }
        }

        /// <remarks/>
        public NewFileLaunch Launch
        {
            get
            {
                return this.launchField;
            }
            set
            {
                this.launchField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Filter
        {
            get
            {
                return this.filterField;
            }
            set
            {
                this.filterField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class NewFileCopy
    {
        private string targetFolderField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TargetFolder
        {
            get
            {
                return this.targetFolderField;
            }
            set
            {
                this.targetFolderField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class NewFileMove
    {
        private string targetFolderField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TargetFolder
        {
            get
            {
                return this.targetFolderField;
            }
            set
            {
                this.targetFolderField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class NewFileLaunch
    {
        private string applicationField;

        private string argumentsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Application
        {
            get
            {
                return this.applicationField;
            }
            set
            {
                this.applicationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Arguments
        {
            get
            {
                return this.argumentsField;
            }
            set
            {
                this.argumentsField = value;
            }
        }
    }*/
}